### ISSUE TITLE
showing error in auth

### ISSUE THREAD

**Issue by arsh911** [theindianappguy/FlutterChatAppTutorial#8]
![Screenshot 2021-01-26 at 10 39 32 PM](https://user-images.githubusercontent.com/78039527/105878793-6afeb300-6027-11eb-82cf-c5cb29b972d4.png)

**Comment by arsh911** [comment]
please help me this!

**Comment by MAH0460** [comment]
> please help me this!
In new version of firebase FirebaseUser is replaced only with User

**Comment by arsh911** [comment]
> > please help me this!
> > Please click on get dependencies on the above popup
> > Make sure to add the latest version of dependencies and multidex in the pubspec.yaml and gradlebuild file from pub.dev .
> > for any help just comment.
> > The first error about user. ===>
> > rename the class and constructor name in user.dart file to AppUser and use AppUser instead of User because User is a firebase method.
> > and then
> > return user != null ? AppUser(userId: user.uid) : null;
> 
> The second error ===>
> In new version of firebase FirebaseUser is replaced only with User. So change the complete function to::::
> AppUser _userFromFirebaseUser(User user){
> return user != null ? AppUser(userId: user.uid) : null;
> }
> 
> The third error will be resolved when you do up above.
> 
> Error no 4 ====>
> In new firebase AuthResults is replaced with UserCredentials. Please do that too.

THANKS ALOT,
can u please tell about authmethods also

**Comment by arsh911** [comment]
> > please help me this!
> > Please click on get dependencies on the above popup
> > Make sure to add the latest version of dependencies and multidex in the pubspec.yaml and gradlebuild file from pub.dev .
> > for any help just comment.
> > The first error about user. ===>
> > rename the class and constructor name in user.dart file to AppUser and use AppUser instead of User because User is a firebase method.
> > and then
> > return user != null ? AppUser(userId: user.uid) : null;
> 
> The second error ===>
> In new version of firebase FirebaseUser is replaced only with User. So change the complete function to::::
> AppUser _userFromFirebaseUser(User user){
> return user != null ? AppUser(userId: user.uid) : null;
> }
> 
> The third error will be resolved when you do up above.
> 
> Error no 4 ====>
> In new firebase AuthResults is replaced with UserCredentials. Please do that too.

THANKS 



![Uploading Screenshot 2021-01-31 at 2.00.02 PM.png…]()

**Comment by MAH0460** [comment]
Your image is not visible.

**Comment by arsh911** [comment]
> > please help me this!
> > Please click on get dependencies on the above popup
> > Make sure to add the latest version of dependencies and multidex in the pubspec.yaml and gradlebuild file from pub.dev .
> > for any help just comment.
> > The first error about user. ===>
> > rename the class and constructor name in user.dart file to AppUser and use AppUser instead of User because User is a firebase method.
> > and then
> > return user != null ? AppUser(userId: user.uid) : null;
> 
> The second error ===>
> In new version of firebase FirebaseUser is replaced only with User. So change the complete function to::::
> AppUser _userFromFirebaseUser(User user){
> return user != null ? AppUser(userId: user.uid) : null;
> }
> 
> The third error will be resolved when you do up above.
> 
> Error no 4 ====>
> In new firebase AuthResults is replaced with UserCredentials. Please do that too.

THANKS 



need more help
![Uploading Screenshot 2021-01-31 at 2.00.02 PM.png…]()

**Comment by arsh911** [comment]
![Screenshot 2021-01-31 at 2 00 02 PM](https://user-images.githubusercontent.com/78039527/106379603-1d8d9780-63d3-11eb-9e13-d37cfc7d587a.png)

**Comment by MAH0460** [comment]
The problem is in the main.dart file
Add the code 

![Screenshot (20)](https://user-images.githubusercontent.com/58516674/106379998-7f4f0100-63d5-11eb-87a0-801221ab9c1c.png)

**Comment by arsh911** [comment]
Performing hot restart...
Syncing files to device Android SDK built for x86 64...
lib/main.dart:9:9: Error: Getter not found: 'Firebase'.
  await Firebase.initializeApp();
        ^^^^^^^^
Restarted application in 1,261ms.

**Comment by MAH0460** [comment]
Attach the screenshot.

**Comment by arsh911** [comment]
![Screenshot 2021-02-13 at 9 15 55 PM](https://user-images.githubusercontent.com/78039527/107854300-07ef8780-6e41-11eb-8554-1b645859a581.png)

**Comment by arsh911** [comment]
please help me

**Comment by MAH0460** [comment]
Please show line number 45 and line number 10

**Comment by MAH0460** [comment]
inside the getLoggedInState function inside the setstate method add the following code. It may help


getLoggedInState () async{
    await HelperFunctions.getUserLoggedInSharedPreference().then((value){
      setState(() {
        if(value != null){
          setState(() {
            userIsLoggedIn = value;
          });
        }
      });
    });
  }

**Comment by arsh911** [comment]
![Screenshot 2021-02-13 at 9 53 23 PM](https://user-images.githubusercontent.com/78039527/107855018-ee047380-6e45-11eb-9da8-d5cb09cd8460.png)

**Comment by arsh911** [comment]
this is also happening since I have updated android
 studio

**Comment by MAH0460** [comment]
Show the main.dart file screenshot

**Comment by MAH0460** [comment]
Try to update flutter or reinstall the sdk at C:\src\flutter. This might help.

**Comment by MAH0460** [comment]
If the issue is solved please close the topic. Thank you.

**Comment by arsh911** [comment]
![Screenshot 2021-02-16 at 6 38 04 PM](https://user-images.githubusercontent.com/78039527/108067108-4cb83000-7086-11eb-8016-795d19a3eaa2.png)

**Comment by arsh911** [comment]
how do I fix this

**Comment by MAH0460** [comment]
Please show me the recent changes which you did before when the error occurred.

**Comment by arsh911** [comment]
![Screenshot 2021-02-16 at 7 34 37 PM](https://user-images.githubusercontent.com/78039527/108073439-0c5cb000-708e-11eb-9898-1173421ddf94.png)

**Comment by arsh911** [comment]
moved DatabaseMethods from inistate  to getuserinfo
and
change snapshot to snapshots

**Comment by arsh911** [comment]
![Uploading Screenshot 2021-02-16 at 7.41.25 PM.png…]()

**Comment by arsh911** [comment]
![Screenshot 2021-02-16 at 7 41 25 PM](https://user-images.githubusercontent.com/78039527/108074390-25b22c00-708f-11eb-874a-39931d8e18c1.png)

**Comment by MAH0460** [comment]
What's your purpose of doing this? My code is working fine when database method is in initState method.

**Comment by arsh911** [comment]
it is not showing data once it is loaded , in the chatroomTile

**Comment by arsh911** [comment]
> What's your purpose of doing this? My code is working fine when database method is in initState method. And please show the database method to getChatRoom

![Screenshot 2021-02-16 at 8 11 19 PM](https://user-images.githubusercontent.com/78039527/108078032-31075680-7093-11eb-93b5-a5a6aeea710d.png)

**Comment by MAH0460** [comment]
Write a mail to me. I'll share the code. Check for mail in my github ID.

**Comment by arsh911** [comment]
plz share here only.

**Comment by MAH0460** [comment]
this is the complete.
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:ourchat/helper/helperfunctions.dart';
import 'package:ourchat/services/database.dart';



class ConversationScreen extends StatefulWidget {
  final String chatRoomId;
  final String thisUserName;
  ConversationScreen(this.chatRoomId, this.thisUserName);

  @override
  _ConversationScreenState createState() => _ConversationScreenState();
}

class _ConversationScreenState extends State<ConversationScreen> {
  String _x;
  DatabaseMethods databaseMethods = new DatabaseMethods();
  TextEditingController messageController = new TextEditingController();

  Stream chatMessageStream;

  Widget chatMessageList(){
    return StreamBuilder(
      stream: chatMessageStream,
        builder: (context, snapshot) {
          return snapshot.hasData ?Container(
            margin: EdgeInsets.only(bottom: 80),
            child: ListView.builder(
              reverse: true,
                  itemCount: snapshot.data.docs.length,
                  itemBuilder: (context, index){
                    return MessageTile(snapshot.data.docs[index].data()["message"],
                        snapshot.data.docs[index].data()["sendBy"] == _x,
                        snapshot.data.docs[index].data()["time2"]);
                  }),
          ) :  Container(
            child: Center(child: CircularProgressIndicator()),
          );
        },
    );
  }

  sendMessage(){
    if(messageController.text.isNotEmpty){
      Map<String, dynamic>messageMap = {
        "message" : messageController.text,
        "sendBy" : _x,
        "time" : DateTime.now().microsecondsSinceEpoch,
        "time2" : DateTime.now().toLocal().toString().substring(5, 16)
      };
      databaseMethods.addConversationMessages(widget.chatRoomId, messageMap);
      messageController.text = "";
    }
  }
  void initState(){
    getUserName();
    databaseMethods.getConversationMessages(widget.chatRoomId).then((value){

      setState(() {
        chatMessageStream = value;
      });
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: Row(
          children: [Container(
            margin: EdgeInsets.only(left: 20, top: 5, bottom: 5),
            padding: EdgeInsets.all(10),
            width: 36,
            height: 36,
            decoration: BoxDecoration(
              color: Colors.blue,
              borderRadius: BorderRadius.circular(30),

            ),
          ),
          ],
        ),
        title: Text(widget.thisUserName, style: TextStyle(
          fontFamily: 'Dancing',
          fontSize: 25,
          fontWeight: FontWeight.bold,

        ),),
      ),
      body :Container(
        child: Stack(
          children: [
            chatMessageList(),
            Container(
              alignment: Alignment.bottomCenter,
              child: Container(
                color: Color(0x54FFFFFF),
                padding: EdgeInsets.symmetric(horizontal: 24, vertical: 16),
                child: Row(
                  children: [
                    Expanded(
                      child: TextField(
                        controller: messageController,
                        style: TextStyle(
                          color: Colors.white,
                        ),
                        decoration: InputDecoration(
                          hintText: "Message...",
                          hintStyle: TextStyle(
                            color: Colors.white54,
                          ),
                          border: InputBorder.none,
                        ),
                      ),
                    ),
                    GestureDetector(
                      onTap: (){
                        sendMessage();
                      },
                      child: Container(
                          height: 40,
                          width: 40,
                          decoration: BoxDecoration(
                              gradient: LinearGradient(
                                colors: [
                                  const Color(0x36FFFFFF),
                                  const Color(0x0FFFFFFF),
                                ],
                              ),
                              borderRadius: BorderRadius.circular(40)
                          ),
                          padding: EdgeInsets.all(12),
                          child: Image.asset("assets/images/send.png")),
                    )
                  ],
                ),
              ),
            ),

          ],
        ),
      )
    );
  }

  getUserName() async{
    _x = await HelperFunctions.getUsernameSharedPreference();
  }
}

class MessageTile extends StatelessWidget {
  final String message;
  final bool isSendByMe;
  final String tim;
  MessageTile(this.message , this.isSendByMe, this.tim);

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.only(left: isSendByMe ?  60: 12,right: isSendByMe ? 24 : 100),
      margin: EdgeInsets.symmetric(vertical: 4),
      width: MediaQuery.of(context).size.width,
      alignment: isSendByMe ? Alignment.centerRight : Alignment.centerLeft,
      child: Column(
        children: [
          Container(
            margin: EdgeInsets.symmetric(vertical: 4),
            padding: EdgeInsets.symmetric(horizontal: 24,vertical: 12),
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: isSendByMe ? [
                    const Color(0xff007EF4),
                    const Color(0xff2A75BC)
                    ]
                      : [
                        const Color(0x1AFFFFFF),
                        const Color(0x1AFFFFFF)
                ]

              ),
              borderRadius: isSendByMe ?
                  BorderRadius.only(
                    topLeft: Radius.circular(23),
                    topRight: Radius.circular(23),
                    bottomLeft: Radius.circular(23)
                  )
                  :
                  BorderRadius.only(
                    topLeft: Radius.circular(23),
                    topRight: Radius.circular(23),
                    bottomRight: Radius.circular(23)
                  )
            ),
            child: Text(message, style: TextStyle(
              color: Colors.white,
              fontSize: 16,
            ),
            ),
          ),
          Container(
            child: Text(tim,textAlign: TextAlign.right, style: TextStyle(
              color: Colors.white,
              fontSize: 10
            ),),
          ),
        ],
      ),
    );
  }
}

**Comment by arsh911** [comment]
![Screenshot 2021-02-18 at 12 22 35 AM](https://user-images.githubusercontent.com/78039527/108253228-8caf0e00-717f-11eb-8229-79e9491c738f.png)

**Comment by arsh911** [comment]
![Screenshot 2021-02-18 at 12 22 35 AM](https://user-images.githubusercontent.com/78039527/108253358-b23c1780-717f-11eb-9334-213509dc2859.png)

**Comment by arsh911** [comment]
I am not able to get this what is on that emulator screen

**Comment by MAH0460** [comment]
This is the home screen, since I have shared the complete conversation screen code, please complete the video tutorial, you will get what it is.

**Comment by arsh911** [comment]
I am  talking about chatroomscreen , my conversation
screen is working fine, and I have completed tutorial too.
